name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: titoasm-linux
          path: target/x86_64-unknown-linux-gnu/release/titoasm

  release:
    runs-on: ubuntu-latest
    needs: [
      build-linux
    ]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display artifacts
        run: ls -R artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            ./artifacts/titoasm-linux/titoasm